### ISSUE TITLE
Add link to download example apps

### ISSUE THREAD

**Issue by ALRubinger** [arun-gupta/wildfly-lab#1]
https://github.com/arun-gupta/wildfly-lab/blob/master/docs/wildfly-lab.html#L698

**Comment by arun-gupta** [comment]
Yep, working on that about now :-)

Refresh your link as I pushed a bunch of changes this morning.

**Comment by ALRubinger** [comment]
Cool.

Just let me know when you're done and I'll do a PDF export of the
instructions and put them on the NAS.

**Comment by arun-gupta** [comment]
Link added.

PDF export is giving an error and filed that as an issue at: https://github.com/opendevise/asciidoctor-pdf/issues/3
